/* =========================================================
   NODEX — product catalogue (shared by every page)
   img: cut-out product in /img  ·  bg: colour of its catalogue panel
   ========================================================= */
window.NODEX_CATEGORIES = [
  { id: "audio", name: "Audio", page: "shop.html?cat=audio" },
  { id: "mobile", name: "Mobile", page: "shop.html?cat=mobile" },
  { id: "gaming", name: "Gaming", page: "shop.html?cat=gaming" },
  { id: "computers", name: "Computers", page: "shop.html?cat=computers" },
  { id: "cameras", name: "Cameras", page: "shop.html?cat=cameras" },
  { id: "accessories", name: "Accessories", page: "shop.html?cat=accessories" },
];

window.NODEX_PRODUCTS = [
  { id: "ndx-751", name: "Pocket Disc NDX-751", cat: "audio", price: 149.9, badge: "NEW", year: 2026, img: "img/disc-product.webp", bg: "#f7c9dc",
    blurb: "The CD is back — anti-skip, Bluetooth and 40 hours of play.",
    colors: ["#f7b8d2", "#c3cad3", "#6f9dff", "#1b1b1f"],
    specs: [["Type", "Portable CD + Bluetooth"], ["Formats", "CD, CD-R, CD-RW, MP3"], ["Anti-skip", "G-Shield 40s"], ["Battery", "40h / 2×AA or USB-C"], ["Weight", "198 g"]] },
  { id: "nx-h101", name: "Spike On-Ear NX-H101", cat: "audio", price: 59, year: 2026, img: "img/audio-headphones.webp", bg: "#ffe27a",
    blurb: "Studded cups, 40mm drivers, zero chill.",
    colors: ["#1b1b1f", "#c3cad3"],
    specs: [["Type", "On-ear, wired"], ["Drivers", "40 mm"], ["Cable", "1.2 m, 3.5 mm jack"], ["Weight", "210 g"]] },
  { id: "mp3-stick", name: "MP3 Stick 4GB", cat: "audio", price: 25, was: 35, badge: "SALE", year: 2006, img: "img/shop-mp3-stick.webp", bg: "#dfe9f5",
    blurb: "Plug it in, drag your songs, go. FM radio included.",
    colors: ["#c3cad3"],
    specs: [["Storage", "4 GB"], ["Battery", "1×AAA, 12h"], ["Extras", "FM radio, voice rec"], ["Connection", "USB-A plug"]] },
  { id: "walkman-s", name: "Walkman S Series Rose", cat: "audio", price: 79, was: 95, badge: "SALE", year: 2011, img: "img/shop-walkman.webp", bg: "#ffdcea",
    blurb: "Slim, pink, 30 hours of music. The pocket jukebox.",
    colors: ["#f2b8c8", "#1b1b1f"],
    specs: [["Maker", "Sony"], ["Storage", "8 GB"], ["Battery", "Up to 30h"], ["Condition", "Refurbished, tested"]] },
  { id: "street-phones", name: "Street On-Ear", cat: "audio", price: 29, was: 39, badge: "SALE", year: 2005, img: "img/shop-street-phones.webp", bg: "#e9eef5",
    blurb: "The featherweight headband everyone wore on the bus.",
    colors: ["#1b1b1f", "#c3cad3"],
    specs: [["Type", "On-ear, open back"], ["Weight", "58 g"], ["Cable", "1.2 m, 3.5 mm jack"]] },
  { id: "studio-max", name: "Studio Max Angel Edition", cat: "audio", price: 429, badge: "NEW", year: 2026, img: "img/shop-studio-max.webp", bg: "#eef1f6",
    blurb: "Noise-cancelling over-ears dressed in a chrome angel charm.",
    colors: ["#e8ebf0"],
    specs: [["Type", "Over-ear, ANC"], ["Battery", "20h"], ["Charm", "Chrome angel, removable"], ["Connection", "Bluetooth"]] },
  { id: "pink-boombox", name: "Pink Cassette Boombox", cat: "audio", price: 139, was: 169, badge: "SALE", year: 2003, img: "img/shop-pink-boombox.webp", bg: "#ffe3ec",
    blurb: "CD, tape and radio in one very pink box.",
    colors: ["#f3c6d3", "#c3cad3"],
    specs: [["Plays", "CD, cassette, FM/AM"], ["Power", "Mains or 6×C"], ["Condition", "Refurbished, tested"]] },
  { id: "cd-boombox", name: "CD Boombox Silver", cat: "audio", price: 59, was: 79, badge: "SALE", year: 2004, img: "img/shop-cd-boombox.webp", bg: "#e4ecf6",
    blurb: "Round, silver, loud. The bedroom-floor classic.",
    colors: ["#c3cad3"],
    specs: [["Plays", "CD, FM radio"], ["Display", "Red LED"], ["Power", "Mains or 6×C"]] },

  { id: "nx-72-pink", name: "NX-72 Candy Pink", cat: "mobile", price: 59, was: 75, badge: "SALE", year: 2002, img: "img/mobile-phone-1.webp", bg: "#ffd0e6",
    blurb: "The bar phone that started it all, in bubblegum pink.",
    colors: ["#ff8fc4", "#c3cad3"],
    specs: [["Type", "Bar phone, refurbished"], ["Screen", "Colour, 128×128"], ["Battery", "Up to 7 days standby"], ["Network", "2G + nano-SIM adapter"]] },
  { id: "nx-72-clear", name: "NX-72 Crystal", cat: "mobile", price: 55, was: 69, badge: "SALE", year: 2000, img: "img/mobile-phone-2.webp", bg: "#dff1ff",
    blurb: "See-through shell, unbreakable reputation.",
    colors: ["#e8eef4"],
    specs: [["Type", "Bar phone, refurbished"], ["Shell", "Transparent"], ["Battery", "Up to 10 days standby"], ["Games", "Snake II, of course"]] },
  { id: "nx-j5", name: "NX-J5 Rose", cat: "mobile", price: 129, badge: "NEW", year: 2026, img: "img/j5-1.webp", bg: "#f6e3d8",
    blurb: "The flip with the swirl — 360° cute from every side.",
    colors: ["#f3e9d6", "#e8b4ae", "#d6dbe3"],
    specs: [["Type", "Flip phone"], ["Network", "5G + Wi-Fi 7"], ["Camera", "Outer + inner"], ["Battery", "2 days"], ["Thickness", "11 mm"]] },
  { id: "nx-7250", name: "NX-7250 Lilac", cat: "mobile", price: 99, badge: "NEW", year: 2026, img: "img/newin-product.webp", bg: "#e4d4f7",
    blurb: "Blooming & growing — the lilac flip of the season.",
    colors: ["#b79bd6", "#d6dbe3"],
    specs: [["Type", "Flip phone"], ["Screen", "Outer mini display"], ["Camera", "2 MP, flash"], ["Battery", "2 days"]] },
  { id: "nx-k1", name: "NX-K1 Ice Blue", cat: "mobile", price: 89, was: 109, badge: "SALE", year: 2006, img: "img/about-small-1.webp", bg: "#cfe0ff",
    blurb: "Razor-thin, ice-cold, still the coolest thing in any pocket.",
    colors: ["#2f4fbf", "#1b1b1f"],
    specs: [["Type", "Flip, refurbished"], ["Thickness", "16 mm"], ["Camera", "2 MP"], ["Battery", "3 days standby"]] },
  { id: "nx-flip-silver", name: "NX-Flip Silver", cat: "mobile", price: 69, was: 89, badge: "SALE", year: 2004, img: "img/about-small-2.webp", bg: "#e6e9ee",
    blurb: "The silver clamshell everyone had. Now it's yours again.",
    colors: ["#c3cad3"],
    specs: [["Type", "Flip, refurbished"], ["Screen", "Colour, 176×220"], ["Ringtones", "40-note polyphonic"], ["Battery", "4 days standby"]] },
  { id: "cookie-pink", name: "Cookie Touch Pink", cat: "mobile", price: 69, year: 2008, img: "img/shop-cookie-pink.webp", bg: "#ffd9ea",
    blurb: "Touchscreen, stylus on a string. Peak 2008 energy.",
    colors: ["#f5b6cf", "#1b1b1f"],
    specs: [["Maker", "LG"], ["Screen", "3\" touch"], ["Extras", "Stylus included"], ["Condition", "Refurbished, tested"]] },
  { id: "sidekick", name: "Sidekick Swivel", cat: "mobile", price: 119, badge: "NEW", year: 2008, img: "img/shop-sidekick.webp", bg: "#dde3ee",
    blurb: "Flip the screen, reveal the keyboard. Texting royalty.",
    colors: ["#2b2f3a", "#c3cad3"],
    specs: [["Type", "Swivel QWERTY"], ["Screen", "Flip-up, colour"], ["Keyboard", "Full, backlit"], ["Condition", "Refurbished, tested"]] },
  { id: "polka-phone", name: "Polka Slide Phone", cat: "mobile", price: 79, year: 2007, img: "img/shop-polka-phone.webp", bg: "#f7e1ea",
    blurb: "Pink with black polka dots, charm strap already attached.",
    colors: ["#1b1b1f", "#f5b6cf"],
    specs: [["Type", "Slider, refurbished"], ["Finish", "Polka dot"], ["Extras", "Bow charm strap"], ["Camera", "2 MP"]] },

  { id: "psp", name: "PSP 3000", cat: "gaming", price: 139, was: 159, badge: "SALE", year: 2008, img: "img/console-psp.webp", bg: "#dfe6f5",
    blurb: "Widescreen handheld, UMD drive, endless nostalgia.",
    colors: ["#e8ecf4", "#1b1b1f"],
    specs: [["Maker", "Sony · 2008"], ["Screen", "4.3\" widescreen"], ["Media", "UMD + Memory Stick"], ["Condition", "Refurbished, tested"]] },
  { id: "wii", name: "Wii", cat: "gaming", price: 89, was: 109, badge: "SALE", year: 2006, img: "img/console-wii.webp", bg: "#d8f1ff",
    blurb: "Motion control that got the whole family off the sofa.",
    colors: ["#f4f5f7"],
    specs: [["Maker", "Nintendo · 2006"], ["Control", "Motion remote"], ["Plays", "Wii + GameCube discs"], ["Condition", "Refurbished, tested"]] },
  { id: "ds-lite", name: "DS Lite", cat: "gaming", price: 79, was: 95, badge: "SALE", year: 2006, img: "img/console-ds-lite.webp", bg: "#e9f0f7",
    blurb: "Two screens, one stylus, a thousand pets to feed.",
    colors: ["#f4f5f7", "#9fc4e8", "#ff8fc4"],
    specs: [["Maker", "Nintendo · 2006"], ["Screens", "Dual, touch"], ["Plays", "DS + GBA carts"], ["Condition", "Refurbished, tested"]] },
  { id: "gba-sp", name: "Game Boy Advance SP", cat: "gaming", price: 69, was: 85, badge: "SALE", year: 2003, img: "img/console-gba-sp.webp", bg: "#ffd6ea",
    blurb: "Clamshell, backlit, pearl pink. Perfect.",
    colors: ["#ffc2e0", "#c3cad3"],
    specs: [["Maker", "Nintendo · 2003"], ["Screen", "Backlit, clamshell"], ["Battery", "Rechargeable"], ["Condition", "Refurbished, tested"]] },
  { id: "ps2", name: "PlayStation 2 Slim", cat: "gaming", price: 99, was: 119, badge: "SALE", year: 2004, img: "img/console-ps2.webp", bg: "#d9dde6",
    blurb: "The best-selling console ever, in its slimmest suit.",
    colors: ["#1b1b1f", "#c3cad3"],
    specs: [["Maker", "Sony · 2004"], ["Media", "DVD + CD"], ["Pads", "1 included"], ["Condition", "Refurbished, tested"]] },
  { id: "gamecube", name: "GameCube", cat: "gaming", price: 119, year: 2001, img: "img/console-gamecube.webp", bg: "#e2dcff",
    blurb: "The lunchbox with a handle. Indigo forever.",
    colors: ["#5b44b8", "#1b1b1f"],
    specs: [["Maker", "Nintendo · 2001"], ["Media", "Mini disc"], ["Pads", "1 included"], ["Condition", "Refurbished, tested"]] },

  { id: "vaio-c1", name: "PictureBook C1", cat: "computers", price: 249, was: 299, badge: "SALE", year: 2001, img: "img/shop-vaio-c1.webp", bg: "#e2e4f5",
    blurb: "A laptop the size of a paperback, with a camera in the lid.",
    colors: ["#9aa0c8"],
    specs: [["Maker", "Sony VAIO"], ["Screen", "8.9\" wide"], ["Camera", "Built-in, swivel"], ["Condition", "Refurbished, new battery"]] },
  { id: "letsnote", name: "Let's note Mini", cat: "computers", price: 299, year: 2009, img: "img/shop-letsnote.webp", bg: "#e8f5d6",
    blurb: "The indestructible mini-laptop with the round trackpad.",
    colors: ["#c3cad3"],
    specs: [["Maker", "Panasonic"], ["Screen", "12.1\""], ["Trackpad", "Round, wheel-scroll"], ["Condition", "Refurbished, Windows reset"]] },
  { id: "clear-keys", name: "Clear Keyboard '02", cat: "computers", price: 109, year: 2026, img: "img/clear-keyboard.webp", bg: "#e6ffb0",
    blurb: "Transparent shell, clicky keys, visible guts.",
    colors: ["#e8eef4", "#9fd4ff"],
    specs: [["Layout", "Full size, ISO"], ["Switches", "Mechanical, clicky"], ["Connection", "USB-C + Bluetooth"], ["Shell", "Transparent"]] },
  { id: "digicam-y2k", name: "IXUS Pocket Digicam", cat: "cameras", price: 149, badge: "NEW", year: 2014, img: "img/digicam.webp", bg: "#ffe0c2",
    blurb: "Flash-on, point-and-shoot photos for the party pics era.",
    colors: ["#3a2a2a", "#c3cad3"],
    specs: [["Maker", "Canon"], ["Sensor", "20 MP"], ["Zoom", "10× optical"], ["Storage", "SD card"]] },
  { id: "handycam-lime", name: "Handycam Lime", cat: "cameras", price: 169, year: 2006, img: "img/shop-handycam-lime.webp", bg: "#e9ffd0",
    blurb: "Lime green, flip screen, stickers included. Film everything.",
    colors: ["#9ed36a"],
    specs: [["Maker", "Sony"], ["Media", "MiniDV tape"], ["Screen", "2.5\" flip-out"], ["Condition", "Refurbished, tested"]] },
  { id: "sd-cam-pink", name: "SD Camcorder Pink", cat: "cameras", price: 129, year: 2009, img: "img/shop-sd-cam-pink.webp", bg: "#ffdce8",
    blurb: "Pocket camcorder that records straight to SD.",
    colors: ["#e8a9bf", "#c3cad3"],
    specs: [["Maker", "Panasonic"], ["Media", "SD card"], ["Zoom", "70× optical"], ["Condition", "Refurbished, tested"]] },
  { id: "hd-cam", name: "HD Handycam Black", cat: "cameras", price: 199, was: 239, badge: "SALE", year: 2013, img: "img/shop-hd-cam.webp", bg: "#e3e6ee",
    blurb: "Full HD with a built-in projector for instant movie night.",
    colors: ["#1b1b1f"],
    specs: [["Maker", "Sony"], ["Video", "Full HD"], ["Extras", "Built-in projector"], ["Condition", "Refurbished, tested"]] },
  { id: "minidv", name: "MiniDV Camcorder Silver", cat: "cameras", price: 119, was: 149, badge: "SALE", year: 2002, img: "img/shop-minidv.webp", bg: "#e6ecf4",
    blurb: "The tape camcorder behind every 2002 birthday video.",
    colors: ["#c3cad3"],
    specs: [["Media", "MiniDV tape"], ["Zoom", "10× optical"], ["Screen", "2.5\" flip-out"], ["Condition", "Refurbished, tested"]] },

  { id: "charm-pack", name: "Charm Strap Pack", cat: "accessories", price: 14, year: 2026, img: "img/charms.webp", bg: "#ffd9ec",
    blurb: "Stars, hearts, octopus and chrome — dress up any phone.",
    colors: ["#ff4fa8", "#c3cad3"],
    specs: [["Pieces", "6 charms + strap"], ["Fits", "Phones, bags, consoles"], ["Material", "Resin + metal"]] },
  { id: "angel-case", name: "Angel Wing Case", cat: "accessories", price: 19, badge: "NEW", year: 2026, img: "img/shop-angel-case.webp", bg: "#eaf2ff",
    blurb: "A clear handheld case with fluffy white wings. Ascend.",
    colors: ["#f4f5f7"],
    specs: [["Fits", "Handheld consoles, 3.5\""], ["Material", "Clear TPU + resin wings"]] },
  { id: "bunny-case", name: "Fluffy Bunny Phone Set", cat: "accessories", price: 24, year: 2026, img: "img/shop-bunny-case.webp", bg: "#fbe4ee",
    blurb: "Plush bunny case with a matching flip phone skin.",
    colors: ["#f4f5f7", "#f5b6cf"],
    specs: [["Includes", "Plush case + skin"], ["Material", "Faux fur, silicone"]] },
  { id: "clear-keychain", name: "Clear Console Keychain", cat: "accessories", price: 12, year: 2026, img: "img/shop-clear-keychain.webp", bg: "#e6f6ff",
    blurb: "A tiny see-through handheld for your keys, with heart charm.",
    colors: ["#e8eef4", "#f5b6cf"],
    specs: [["Size", "6 cm"], ["Material", "Clear acrylic"], ["Charm", "Pink heart"]] },
  { id: "angel-buds", name: "Angel Wing Earbuds", cat: "accessories", price: 39, year: 2026, img: "img/shop-angel-buds.webp", bg: "#eef1f8",
    blurb: "Wired earbuds with little wings. Heaven, on shuffle.",
    colors: ["#f4f5f7"],
    specs: [["Type", "Wired, 3.5 mm"], ["Cable", "1.2 m"], ["Wings", "Removable silicone"]] },
  { id: "bunny-pouch", name: "Bunny Gadget Pouch", cat: "accessories", price: 22, was: 29, badge: "SALE", year: 2026, img: "img/shop-bunny-pouch.webp", bg: "#f6f1e6",
    blurb: "Zip pouch for earbuds, cables and small consoles.",
    colors: ["#f4f5f7"],
    specs: [["Size", "12 × 10 cm"], ["Inside", "Mesh pocket + strap"], ["Fits", "DS, GBA, earbuds"]] },
  { id: "pocket-pet", name: "Pocket Pet Pearl", cat: "accessories", price: 29, year: 2026, img: "img/shop-pocket-pet.webp", bg: "#f2e8f8",
    blurb: "A virtual pet in a pearl egg, bows and charms included.",
    colors: ["#e4d4f0", "#f5b6cf"],
    specs: [["Type", "Virtual pet"], ["Screen", "Colour LCD"], ["Battery", "Rechargeable"], ["Extras", "Charm chain"]] },
];

/* ---------------------------------------------------------
   Deals-only items (hidden from the shop grid):
   bundles are priced from their pieces minus the set discount,
   lucky bags are mystery bags with a guaranteed value.
   --------------------------------------------------------- */
(() => {
  const P = window.NODEX_PRODUCTS;
  const byId = (id) => P.find((p) => p.id === id);
  const BUNDLES = [
    { id: "set-handheld", name: "Handheld Heaven Set", off: .15, items: ["psp", "angel-case", "charm-pack"], img: "img/console-psp.webp", bg: "#dfe6f5",
      blurb: "PSP 3000 + Angel Wing Case + Charm Strap Pack." },
    { id: "set-music", name: "Music Play Set", off: .12, items: ["ndx-751", "nx-h101"], img: "img/disc-product.webp", bg: "#f7c9dc",
      blurb: "Pocket Disc NDX-751 + Spike On-Ear headphones." },
    { id: "set-camcorder", name: "Rec ● Starter Set", off: .15, items: ["handycam-lime", "bunny-pouch", "charm-pack"], img: "img/shop-handycam-lime.webp", bg: "#e9ffd0",
      blurb: "Handycam Lime + Bunny Gadget Pouch + Charm Strap Pack." },
    { id: "set-flip", name: "Flip Phone Duo", off: .18, items: ["nx-flip-silver", "nx-72-pink"], img: "img/about-small-2.webp", bg: "#e6e9ee",
      blurb: "NX-Flip Silver + NX-72 Candy Pink. One for you, one for your bestie." },
  ];
  BUNDLES.forEach((b) => {
    const parts = b.items.map(byId).filter(Boolean);
    const full = parts.reduce((s, p) => s + p.price, 0);
    P.push({ ...b, cat: "accessories", hidden: true, bundle: b.items, year: 2026,
      was: Math.round(full * 100) / 100, price: Math.round(full * (1 - b.off)), colors: ["#1b1b1f"],
      specs: parts.map((p) => ["Includes", p.name]) });
  });
  [
    { id: "lucky-s", name: "Lucky Bag S", price: 29, value: 45 },
    { id: "lucky-m", name: "Lucky Bag M", price: 59, value: 95 },
    { id: "lucky-l", name: "Lucky Bag L", price: 99, value: 160 },
  ].forEach((l) => P.push({ ...l, cat: "accessories", hidden: true, lucky: true, year: 2026, img: "img/deals-lucky-bag.webp", bg: "#ffe100",
    blurb: `A mystery bag worth at least €${l.value}.`, colors: ["#e10600"], specs: [["Guaranteed value", "€" + l.value + "+"]] }));
})();

/* ---------------------------------------------------------
   BRANDS — makers + NODEX's own lines.
   Names only, in NODEX's own type: no third-party logos.
   --------------------------------------------------------- */
window.NODEX_BRANDS = [
  { id: "sony", name: "Sony", since: 1946, hq: "Tokyo, JP", jp: "ソニー", known: "Walkman, PlayStation, Handycam",
    blurb: "The company that put music in your pocket and a console under every TV.", mood: "Chrome, black, electric blue",
    items: ["psp", "ps2", "walkman-s", "vaio-c1", "handycam-lime", "hd-cam"] },
  { id: "nintendo", name: "Nintendo", since: 1889, hq: "Kyoto, JP", jp: "任天堂", known: "Game Boy, DS, Wii",
    blurb: "Started with playing cards, ended up in every backpack on earth.", mood: "Pearl pink, indigo, white",
    items: ["wii", "ds-lite", "gba-sp", "gamecube"] },
  { id: "canon", name: "Canon", since: 1937, hq: "Tokyo, JP", jp: "キヤノン", known: "Compact digicams",
    blurb: "The pocket camera behind a thousand party pictures with the flash on.", mood: "Black, silver, flash-white",
    items: ["digicam-y2k"] },
  { id: "panasonic", name: "Panasonic", since: 1918, hq: "Osaka, JP", jp: "パナソニック", known: "Let’s note, SD camcorders",
    blurb: "Tough little laptops and pocket camcorders built to last forever.", mood: "Silver, pink, practical",
    items: ["letsnote", "sd-cam-pink"] },
  { id: "lg", name: "LG", since: 1947, hq: "Seoul, KR", jp: "エルジー", known: "Cookie & Chocolate phones",
    blurb: "Touchscreens with a stylus on a string, before touchscreens were everywhere.", mood: "Candy pink, gloss black",
    items: ["cookie-pink"] },
  { id: "nodex", name: "NODEX", since: 2026, hq: "Milano, IT", jp: "ノーデックス", known: "NX phones, Pocket Disc", house: true,
    blurb: "Our own line: 2002 shapes rebuilt with 2026 insides. Flip, play, repeat.", mood: "Lilac, chrome, candy",
    items: ["ndx-751", "nx-h101", "studio-max", "nx-72-pink", "nx-72-clear", "nx-j5", "nx-7250", "nx-k1", "nx-flip-silver", "clear-keys"] },
  { id: "nodex-vintage", name: "NODEX Vintage", since: 2026, hq: "Milano, IT", jp: "ヴィンテージ", known: "Hand-picked retro finds", house: true,
    blurb: "Unbranded treasures from flea markets and old stockrooms, cleaned and tested.", mood: "Dusty silver, boombox pink",
    items: ["mp3-stick", "street-phones", "pink-boombox", "cd-boombox", "minidv", "sidekick", "polka-phone"] },
  { id: "nodex-charms", name: "NODEX Charms", since: 2026, hq: "Milano, IT", jp: "チャーム", known: "Charms, cases, wings", house: true,
    blurb: "Everything your gadgets want to wear: wings, bunnies, pearls and chrome.", mood: "Pastel, sparkle, fluff",
    items: ["charm-pack", "angel-case", "bunny-case", "clear-keychain", "angel-buds", "bunny-pouch", "pocket-pet"] },
];
window.NODEX_BRANDS.forEach((b) => b.items.forEach((id) => {
  const p = window.NODEX_PRODUCTS.find((x) => x.id === id);
  if (p) p.brand = b.id;
}));
